### ISSUE TITLE
求助，在photos框架下怎么保存gif图片啊？

### ISSUE THREAD

**Issue by Charles2016** [jh235/SaveGifImage#1]
creationRequestForAssetFromImageData 这个方法在新的相册API中没有找到...

**Comment by jh235** [comment]
@Charles2016 为什么要用photos框架呢,我没有用过photos框架. 你说的我不太清除

**Comment by Charles2016** [comment]
为了适配iOS8及以上的啊，额，不清楚就算了，多谢你的Demo...
